### ISSUE TITLE
Wecker missing in App Store

### ISSUE THREAD

**Issue by ghost** [MrJohnZoidberg/Snips-Wecker#1]
Hi Domi,

dein Wecker Skill sieht echt sehr nice aus!
Leider ist er nicht mehr im App Store zu finden.

**Comment by dominiczedler** [comment]
Hi, danke für das Lob!
Die App habe ich heute im Store veröffentlicht. Aber z.B. die Snooze-Funktion geht noch nicht und Captcha auch noch nicht, also es braucht noch ein bisschen Zeit, bis alles funktioniert.
