### ISSUE TITLE
add text to reminder

### ISSUE THREAD

**Issue by ccoenen** [MrJohnZoidberg/Snips-Wecker#5]
This would be super useful, especially when multiple alarms are running. The text / topic / description or whatever it's called could then somehow be mentioned along with the alarm.

```
Hey Snips, remind me in 10 minutes to take the pizza out
Hey Snips, remind me about washing tomorrow
Hey Snips, in 5 minutes my tea will be ready
Hey Snips, remind me to pick up a package at 15:00
```

**Comment by dominiczedler** [comment]
Hi, yes I already thought about that. But there are several problems at this time:

1. Snips can't recognize the words which are not in the console. I would prefer to create another app "Timers" which contains some of them, but in my opinion that's not a good solution.

2. The alarm clock works with hours and minutes - so if you want to create a reminder for 30 seconds, it's not working. This is also another point why I would make the other app "Timers".

3. "Hey Snips, remind me about washing tomorrow" would create an alarm at 0:00 tomorrow. For this I wanted to create an app "Reminders", but there is the problem again with the understanding of words.

You see there is a lot to do for this and sadly I currently have no time to do it.
