### ISSUE TITLE
how long until ...?

### ISSUE THREAD

**Issue by ccoenen** [MrJohnZoidberg/Snips-Wecker#6]
I would like to query the alarms in relative time like this:

```
Hey Snips, how long to the next alarm
-> "the next alarm will be in 11 minutes" (or similar)
```

I often know when an alarm will go off (at 15:00 for example), but I don't care for the wall clock time, just for the duration left until I need to take some action. So the reply "11 minutes" sometimes makes more sense than "at 15:00" - "what time is it?" - "14:49" - aha 11 minutes, I still have time to do a short task in the meantime.

**Comment by dominiczedler** [comment]
Done.

**Get next alarm:**

    Wann klingelt in der Küche der nächste Alarm?
    Was ist der nächste Alarm?
    Kannst du mir sagen wann der nächste Alarm klingelt?
    In wie vielen Stunden klingelt hier der nächste Alarm?
    Sage mir wann der nächste Alarm klingelt.
    Wann ist der nächste Wecker gestellt?
    Wann klingelt der nächste Alarm im Bad?
    Ich will wissen wann im Schlafzimmer der nächste Alarm los geht.
