### ISSUE TITLE
action domi-Wecker failed 3 times in the last 10 seconds, disabling it

### ISSUE THREAD

**Issue by patttiii** [MrJohnZoidberg/Snips-Wecker#7]
Hallo, vielen Dank für deine coole App!

Ich habe die App über `sam install skills ` zu meinem Assistenten hinzugefügt. Nun habe ich meine App modifiziert habe und wieder `sam install skills ` ausgeführt. Seitdem bekomme ich diese Felhlermeldung:

`Mar 11 11:26:15 snips snips-skill-server[15607]: INFO:snips_skill_server_lib::runner            : [domi-Wecker][err] Traceback (most recent call last):
Mar 11 11:26:15 snips snips-skill-server[15607]: INFO:snips_skill_server_lib::runner            : [domi-Wecker][err]   File "./action-domi-Wecker.py", line 118, in <module>
Mar 11 11:26:15 snips snips-skill-server[15607]: INFO:snips_skill_server_lib::runner            : [domi-Wecker][err]     alarmclock = AlarmClock(config)
Mar 11 11:26:15 snips snips-skill-server[15607]: INFO:snips_skill_server_lib::runner            : [domi-Wecker][err]   File "/var/lib/snips/skills/Snips-Wecker/alarmclock/alarmclock.py", line 22, in __init__
Mar 11 11:26:15 snips snips-skill-server[15607]: INFO:snips_skill_server_lib::runner            : [domi-Wecker][err]     self.dict_siteids = self.config['dict_site-id']
Mar 11 11:26:15 snips snips-skill-server[15607]: INFO:snips_skill_server_lib::runner            : [domi-Wecker][err] KeyError: 'dict_site-id'
Mar 11 11:26:15 snips snips-skill-server[15607]: WARN:snips_skill_server_lib::handler::nosandbox: child domi-Wecker has stopped with status `exit code: 1`
Mar 11 11:26:15 snips snips-skill-server[15607]: ERROR:snips_skill_server_lib::runner            : action domi-Wecker failed 3 times in the last 10 seconds, disabling it`

Meine App kann ich als Fehlerquelle weitgehend ausschließen, da ich alle Änderungen wieder rückgängig gemacht habe, der Fehler aber trotzdem bleibt.

**Comment by diplix** [comment]
there seems to be a mismatch between different versions of the `config.ini` file. the room:site_id configuration supposed to be:
`dict_site-id=Schlafzimmer:default`

but while deploying a config file with this entry is created by `sam update-assistant`:
`dict_siteids=Schlafzimmer:default`

this does not match, so you’ll have to manually alter the `/var/lib/snips/skills/Snips-Wecker/config.ini` after each deployment. at least changing `dict_siteids` to `dict_site-id` fixed the problem for me. you’ll need to restart the skill-server afterwards, of course: `sudo systemctl restart snips-skill-server`

**Comment by dominiczedler** [comment]
Sorry, ich werde für die Issues irgendwie nicht benachrichtigt :/
Also die Entwickler haben es mittlerweile so gemacht, dass in der Console nur noch Parameter eingetragen werden können, wenn es ein Code-Snippet ist,. Da das hier nicht der Fall ist, werden ab jetzt alle Parameter über SAM abgefragt.
Ich aktualisiere die App mal in den nächsten Tagen.

**Comment by dominiczedler** [comment]
Done.
