### ISSUE TITLE
MQTT nur auf localhost?

### ISSUE THREAD

**Issue by dnknth** [MrJohnZoidberg/Snips-Wecker#9]
Bei Multi-Room-Installationen mit einem zentralen MQTT-Broker kommt die MQTT-Verbindung nicht zustande, weil diese in `alarmclock/alarmclock.py`, Zeile 26 hart auf `localhost` gesetzt ist.

Könnte man stattdessen nicht die Verbindungsdaten aus `/etc/snips.toml` benutzen?
Code-Beispiel siehe: [SnipsConfig](https://github.com/koenvervloesem/snipskit/blob/master/src/snipskit/config.py) in [koenvervloesem/snipskit](https://github.com/koenvervloesem/snipskit).

**Comment by happenpappen** [comment]
Hatte dasselbe Problem mit der Snips Version 0.63.2 und konnte das mit dem angehängten Patch beheben.

[Snips-Wecker-patch.txt](https://github.com/MrJohnZoidberg/Snips-Wecker/files/3309299/Snips-Wecker-patch.txt)

**Comment by dominiczedler** [comment]
Dieser [Commit](https://github.com/MrJohnZoidberg/Snips-Wecker/commit/62495084380bd2c263d6422203f2b0857315253b) hat das behoben.
Sorry für die späte Antwort.
